window.translations = {
  'Gallery_Hover_Download_FreeImages_Text': 'Посетители смогут скачать ваши фотографии (но не бесплатные фото Wix).',
  'Gallery_ArtStore_User_ProviderDown_Message': 'Извините, произошла техническая ошибка, и мы не можем загрузить Wix Art Store. Обновите страницу или зайдите позже.',
  'Gallery_ArtStore_Organize_Images_EmptyState_Get_Started': 'Начать',
  'Gallery_Sharing_Disabled_In_Editor': 'Чтобы проверить, как это работает, зайдите на опубликованный сайт.',
  'Gallery _CartView_Cart_Label': 'Корзина',
  'Gallery_ArtStore_Cart_Settings_Design_Font_Style_Label': 'Стиль и цвет шрифта',
  'Gallery_ArtStore_UOU_TermsOfUse_Label': 'Условия использования',
  'Gallery_Empty_Description2': 'нажмите «Управлять медиа», чтобы начать',
  'Gallery_ArtStore_Cart_Settings_Design_Menu_Main_Label': 'Main',
  'Gallery_ArtStore_UoU_ProviderDown_Message': 'Извините, возникла техническая проблема. Пожалуйста, обновите страницу или зайдите позже.',
  'Gallery_Empty_Title2': 'сногсшибательная галерея',
  'Gallery_ArtStore_Cart_Settings_Design_Font_Style_Tooltip_Title': 'Customize Font Style',
  'Gallery_ArtStore_ExpandMode_User_Message_Upload_Images': 'Продавать можно только изображение, принадлежащие вам. Чтобы загрузить ваши изображения, нажмите «Управлять медиа».',
  'Gallery_ArtStore_UOU_Add_To_Cart_Button': 'Добавить в корзину',
  'Gallery_ArtStore_Cart_Settings_Design_Select_Layout_Label': 'Select Layout',
  'Gallery_ArtStore_Organize_Images_EmptyState_Header': 'Создайте собственный арт-магазин',
  'Gallery_ArtStore_Organize_Images_EmptyState_Text': 'Начните с добавления изображений в высоком качестве',
  'Gallery_ArtStore_UOU_Select_License_Label': 'Select License',
  'Gallery_ArtStore_Cart_Settings_Design_Button_Default_Text': 'Cart',
  'Gallery_Empty_Title': 'Скоро здесь будет ваша',
  'Gallery_UOU_No_Online_Payment_Screen_Text': 'К сожалению, оформить заказ временно невозможно. Чтобы купить выбранные работы, пожалуйста, свяжитесь с нами.',
  'Gallery_Item_DefaultTitle_Long_Label': 'Название или заголовок',
  'Gallery_ArtStore_Cart_Settings_Design_Menu_Design_Label': 'Design',
  'Gallery_ArtStore_Cart_Settings_Main_Button': 'Customize Icon',
  'Gallery_Item_DefaultDescription_Long_Label': 'Добавьте описание и расскажите о фото или видео подробнее: где и когда снято, на какое оборудование, что вас вдохновило.',
  'Gallery_ArtStore_Cart_Settings_Main_Text': 'Customize your mini cart with a different style and color',
  'Gallery_User_Set_Payment_Screen_Text': 'Пока вы не настроите способ оплаты, покупатели не смогут ничего купить. Чтобы настроить способ оплаты, зайдите во вкладку «Магазин» и нажмите «Настроить оплату».',
  'Gallery_Item_DefaultLink_Label': 'Зайдите на Wix.com',
  'Gallery_Item_DefaultTitle_Short_Label': 'Add a catchy title',
  'Gallery_OnStage_UoU_BuyNow_Label': 'Купить',
  'Gallery_ArtStore_Cart_Settings_Design_Font_Style_Tooltip_Text': 'Choose from a variety of font styles and colors to customize the look & feel of your cart.',
  'Gallery_Item_DefaultDescription_Short_Label': 'Tell your visitors a little about your item.',
  'Gallery_User_Set_Payment_Screen_Ok_Button': 'ОК',
  'Gallery_User_Set_Payment_Screen_Header': 'Настройте способ оплаты, чтобы принимать платежи',
  'Gallery_ArtStore_Cart_Settings_Design_Button_Text_Label': 'Button Text',
  'Gallery_ArtStore_UOU_Continue_Checkout_Label': 'Перейти к оформлению',
  'Gallery_OnStage_UoU_ImageTitle_Label': 'Название изображения',
  'Gallery_OnStage_UoU_Welcome_Text': 'Добро пожаловать в арт-магазин. Чтобы купить фото, кликните по нему.',
  'Gallery_Empty_Description': 'Добавьте фотографии, видео и тексты:',
  'Gallery_Read_Less': 'Read Less',
  'Gallery_UOU_No_Online_Payment_Screen_Ok_Button': 'OK',
  'Gallery_ArtStore_Cart_Settings_Design_Icon_Color_Label': 'Icon Color',
  'Gallery_ArtStore_Organize_Images_EmptyState_Header2': 'и продавайте творческие работы',
  'Gallery_Read_More': 'Раскрыть'
}